kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-discovery-client
rules:
  - apiGroups: [ "" ] # "" indicates the core API group
    resources: [ "services", "pods", "configmaps", "endpoints" ]
    verbs: [ "get", "watch", "list" ]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: microservicios-vfnpoc
  name: namespace-reader
rules:
  - apiGroups: [ "", "extensions", "apps" ]
    resources: [ "configmaps", "pods", "services", "endpoints", "secrets" ]
    verbs: [ "get", "list", "watch" ]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-reader-binding
  namespace: microservicios-vfnpoc
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""