documentation:
  swagger:
    services:
      - name: EmployeeService
        url: http://employee:8080/v2/api-docs
        version: 2.0
      - name: DepartmentService
        url: http://department:8080/v2/api-docs
        version: 2.0
      - name: OrganizationService
        url: http://organization:8080/v2/api-docs
        version: 2.0